In [10]:
import numpy as np

distance1 = np.array([[0.1], [0.2], [0.3]])
distance2 = np.array([[0.4], [0.5], [0.6]])

print(distance1.shape)
print(distance2.shape)
predictions = (distance1 < distance2).astype(int)
print(predictions.shape)

(3, 1)
(3, 1)
(3, 1)


In [12]:
import numpy as np

distance1 = np.array([0.1, 0.2, 0.3])
distance2 = np.array([0.4, 0.5, 0.6])

print(distance1.shape)
print(distance2.shape)
predictions = (distance1 < distance2).astype(int)
print(predictions.shape)

(3,)
(3,)
(3,)


In [11]:
import numpy as np

# 假设 self.A 是一个 2x2 的数组
A = np.array([[1, 2], [3, 4]])
# 假设 self.beta 是一个长度为 2 的数组
beta = np.array([[0.000], [0.002]])

# 生成布尔数组
mask = beta > 1e-5
mask = mask.flatten()
print(A[mask])


[[3 4]]


In [13]:
A = np.array([[1, 2], [3, 4], [5, 6]])  # 3x2
x = np.array([1,2]) # 3,
print(A.shape)
print(x.shape)
print(np.dot(A, x).shape)

(3, 2)
(2,)
(3,)


In [14]:
import numpy as np

# 创建一个一维 numpy 数组
arr1 = np.array([1, 2, 3])
arr2 = np.array([4,5,6])
# 创建一个空列表
my_list = []

# 将一维 numpy 数组追加到列表中
my_list.append(arr1)
my_list.append(arr2)

print(np.array(my_list).T)

[[1 4]
 [2 5]
 [3 6]]


In [15]:
A = np.array([[1, 2], [3, 4], [5, 6]])  # 3x2
x = np.array([
    [1],
    [2]
]) # 3,
print(A.shape)
print(x.shape)
print(np.dot(A, x).shape)

(3, 2)
(2, 1)
(3, 1)


In [16]:
import numpy as np
A = np.array([[1, 2], [3, 4], [5, 6]])  # 3x2
B = np.array([[1, 2], [3, 4], [5, 6]])  # 3x2
print(np.vstack((A, B)))

[[1 2]
 [3 4]
 [5 6]
 [1 2]
 [3 4]
 [5 6]]


In [ ]:
a = 'zhong'
b = 'qian'+a+'hao'
print(b)

qianzhonghao


In [ ]:
import numpy as np

# 使用 np.linspace 在0到10之间生成5个等间隔的数字
linspace_result = np.linspace(0, 10, num=5)
print("使用 np.linspace 生成的结果：", linspace_result)

# 使用 np.arange 从0开始，以2为步长，生成小于10的数字
arange_result = np.arange(0, 10, 2)
print("使用 np.arange 生成的结果：", arange_result)
    

使用 np.linspace 生成的结果： [ 0.   2.5  5.   7.5 10. ]
使用 np.arange 生成的结果： [0 2 4 6 8]


In [ ]:
label_cols = {
    'birds': slice(-19, None),  # 假设 birds 数据集最后 19 列是标签列
    'emotions': slice(-6, None),  # 假设 emotions 数据集最后 6 列是标签列
    'flags': slice(-7, None),  # 假设 flags 数据集最后 7 列是标签列
    'yeast': slice(-14, None)  # 假设 yeast 数据集最后 14 列是标签列   
}



In [7]:
import numpy as np
a = np.array(
[[1, 1, 1],
 [0, 1, 0],
 [0, 0, 1]]
)
b = np.array(
[[1, 0, 1],
 [0, 0, 0],
 [0, 1, 1]]
)
print(a==b)
print(np.mean(a==b,axis=1))

[[ True False  True]
 [ True False  True]
 [ True False  True]]
[0.66666667 0.66666667 0.66666667]


In [8]:
import time
import numpy as np

# 生成一个 1000x1000 的随机矩阵
A = np.random.rand(1000, 1000)
B = np.random.rand(1000, 1000)

# 计算矩阵乘法的时间
start_time = time.time()
C = np.dot(A, B)
end_time = time.time()
print("矩阵乘法的时间：", end_time - start_time)

矩阵乘法的时间： 0.03298306465148926


In [25]:
import numpy as np
from sklearn.neighbors import NearestNeighbors
import time
# 示例数据
m, n = 1500,100
C = np.random.rand(m, n)  # 原矩阵C
x = np.random.rand(n)     # 查询向量x


t1 = time.time()
# 创建KNN模型并拟合原矩阵C
k = 5
knn = NearestNeighbors(n_neighbors=k)
knn.fit(C)  

# 查询x的最近邻索引
_, indices = knn.kneighbors(x.reshape(1, -1))  # 返回的indices直接对应C的行号

t2 = time.time()
print("查询时间：", t2 - t1)

# 提取结果（注意indices是二维数组，取第一个元素）
neighbor_row_indices = indices[0]

print("最近邻在C中的行号:", neighbor_row_indices)


查询时间： 0.005548954010009766
最近邻在C中的行号: [106 992 734 343 217]


In [28]:
import numpy as np
a = np.array([
   [1,2,3,4],
   [3,3,3,3],
   [5,5,6,7]
])
for row in a:
    print(row)
    print(row.shape)

[1 2 3 4]
(4,)
[3 3 3 3]
(4,)
[5 5 6 7]
(4,)


In [36]:
import numpy as np
a = np.array([
   [1,1,0,1],
   [0,1,0,0],
   [0,1,1,0]
])
b = np.array([
   [3,2,1,1],
   [1,1,3,0],
   [4,1,1,0]
])
y = a[:,0]
print(y)
# 提取y中为1的索引
idx = (y==1)
print(b[y==1])


[1 0 0]
[[3 2 1 1]]


In [45]:
import numpy as np
from sklearn.neighbors import NearestNeighbors





def get_V(X,Y,k):
    m = Y.shape[1]
    knn = NearestNeighbors(n_neighbors=k)
    knn.fit(X)
    V = []
    for i in range(m):
        y = Y[:,i]
        B = X[(y==0)]
        v = []
        for x in B:
            _, indices = knn.kneighbors(x.reshape(1, -1)) 
            neighbor_idx = indices[0]
            yy = y[neighbor_idx]
            v.append(np.mean(yy))
    V.append(v)
    return V



print(get_V(a,b,2))

[[np.float64(0.0), np.float64(0.0)]]


In [ ]:
a = [[1,2,3],
     [2,2,2,2,2],
     [1,2,2,2],
     [1]
     ]
print(a[3])

[1]


In [60]:
import numpy as np
a = np.ones(3)
b = np.ones(4)
c = np.ones(5)
d = np.ones(6)
ee = []
ee.append(a)
ee.append(b)
ee.append(c)
ee.append(d)
print(ee[1])

[1. 1. 1. 1.]


In [5]:
import numpy as np
a = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15]])
aa = a.T @ a
print(aa)

b = np.array([1,2,3,4,5])

c = b@aa@b

print(c)

[[158 176 194 212 230]
 [176 197 218 239 260]
 [194 218 242 266 290]
 [212 239 266 293 320]
 [230 260 290 320 350]]
61950


In [13]:
import numpy as np
D_pos = np.array([2,2,2,1,1])
D_neg = np.array([1,1,1,2,2])

D = np.maximum(D_pos,D_neg)
d = np.minimum(D_pos,D_neg)
temp = (d**2)/D

idx1 = (D_pos > D_neg)
idx2 = (D_pos < D_neg)


f = np.zeros(5)
f[idx1] = temp[idx1]
f[idx2] = -temp[idx2]
print(f)
def sigmod(x):
    return 1/(1+np.exp(-x))
print(sigmod(f))

[ 0.5  0.5  0.5 -0.5 -0.5]
[0.62245933 0.62245933 0.62245933 0.37754067 0.37754067]


In [8]:
import numpy as np
D_pos = np.array([2,2,2,1,1])
D_neg = np.array([1,1,1,2,2])
print(D_neg*D_pos)

[2 2 2 2 2]


In [5]:
import numpy as np
a = np.ones(129)
# 生成65*129的矩阵
b = np.ones((65,129))
print((b@a).shape)

(65,)


好的，用户现在问的问题是，为什么当使用NumPy时，b@a可以运行而a@b会报错，尽管一维的numpy数组据说可以自适应形状。用户可能之前遇到了类似的矩阵乘法维度不匹配的问题，现在在理解NumPy的矩阵乘法规则时存在疑惑。

首先，我需要回忆NumPy中的矩阵乘法规则，尤其是对于一维数组的处理。根据官方文档，@运算符在NumPy中执行的是矩阵乘法，对于一维数组，NumPy会将其视为行向量或列向量，但具体行为可能和用户的预期不同。

用户提供的例子是：
a = np.ones(129)  # 形状(129,)
b = np.ones((65,129))  # 形状(65,129)

当执行b@a时，得到的结果形状是(65,)，而a@b则会报错。用户可能认为一维数组可以自动转置以适应乘法，但实际情况并非如此。

接下来，我需要详细分析这两个操作的不同之处。矩阵乘法对于二维数组来说是明确的，但当其中一个操作数是一维数组时，NumPy会如何处理？

首先，b@a的情况：b的形状是(65,129)，a的形状是(129,)。根据NumPy的广播规则，在进行矩阵乘法时，一维数组会被视为列向量，但这里可能被当作行向量处理。实际上，当矩阵乘以一维数组时，NumPy会将一维数组当作一个行向量，结果会得到一个一维数组，形状为(65,)。这相当于将a作为列向量进行乘法，即b乘以a，结果是一个长度为65的数组。

而a@b的情况：a的形状(129,)与b的形状(65,129)相乘。按照矩阵乘法规则，第一个数组的列数必须等于第二个数组的行数。但这里，a是(129,)，而b是(65,129)。如果尝试将a视为行向量（1,129），那么与b（65,129）相乘时，矩阵乘法的条件是第一个数组的列数等于第二个数组的行数，即129和65不匹配，因此会报错。

这里的关键在于，当一维数组在左边时，它被视为行向量，而在右边时被视为列向量。但矩阵乘法需要满足维度匹配，所以在不同的位置会有不同的结果。

用户可能误解了“自适应形状”的含义，以为NumPy会自动调整一维数组的方向来适应乘法，但实际上，NumPy的处理是有一定规则的。一维数组在矩阵乘法中的行为可能并不如用户预期的那样灵活，尤其是在涉及不同维度时。

此外，用户可能的问题背景是之前在处理机器学习模型中的核矩阵乘法时遇到了维度不匹配的错误，现在在调试过程中遇到了类似的形状问题，因此想通过这个例子来理解背后的原因，以便更好地调整自己的代码。

总结来说，用户需要理解在矩阵乘法中，一维数组的位置决定了其被视为行向量还是列向量，而这会影响乘法的合法性。例如，当一维数组在右侧时，它被视为列向量，可以与矩阵相乘，而在左侧时则被视为行向量，需要满足不同的维度条件。




在NumPy中，矩阵乘法（`@`运算符）对一维数组的处理规则如下：

### 1. **`b @ a` 的情况（允许）**
• **`b` 的形状**：`(65, 129)`（二维数组，可视为 65 行 129 列的矩阵）。
• **`a` 的形状**：`(129,)`（一维数组，NumPy 会将其隐式转换为 `(129, 1)` 的列向量）。
• **运算规则**：矩阵乘法 `b @ a` 的实际操作是：  
  将 `a` 视为列向量，相当于计算 `(65, 129) @ (129, 1)` → 结果为 `(65, 1)`，但 NumPy 会自动将结果压缩成一维数组 `(65,)`。

### 2. **`a @ b` 的情况（报错）**
• **`a` 的形状**：`(129,)`（一维数组，NumPy 会将其隐式转换为 `(1, 129)` 的行向量）。
• **`b` 的形状**：`(65, 129)`（二维数组）。
• **运算规则**：矩阵乘法 `a @ b` 的实际操作是：  
  将 `a` 视为行向量，相当于计算 `(1, 129) @ (65, 129)` → **维度不匹配**（129 ≠ 65），因此报错。

---

### 总结规则
| 操作         | 左侧数组形状 | 右侧数组形状 | 隐式转换后的形状 | 是否允许运算      |
|--------------|--------------|--------------|------------------|------------------|
| `b @ a`      | `(65, 129)`  | `(129,)`     | `(65,129) @ (129,1)` | ✅ 允许，结果为 `(65,)` |
| `a @ b`      | `(129,)`     | `(65, 129)`  | `(1,129) @ (65,129)` | ❌ 报错（129 ≠ 65） |

---

### 解决方法
如果想让 `a @ b` 合法，需显式调整维度：
```python
a = np.ones(129)
b = np.ones((65, 129))

# 将 a 显式转换为二维行向量 (1, 129)
a_row = a.reshape(1, -1)  # 形状 (1, 129)
result = a_row @ b.T      # 计算 (1,129) @ (129,65) → 结果形状 (1,65)
```

---

### 附：一维数组的广播规则
在 NumPy 中，一维数组的“自适应”行为遵循以下规则：
• 在矩阵乘法中：
  • **左侧的一维数组**被隐式视为 **行向量**（形状 `(1, n)`）。
  • **右侧的一维数组**被隐式视为 **列向量**（形状 `(n, 1)`）。
• 如果维度不匹配（例如 `(1,129) @ (65,129)`），直接报错，不会自动转置。

建议在涉及多维运算时，始终显式使用二维数组（如 `reshape` 或 `np.newaxis`）以确保维度清晰可控。