In [10]:
import numpy as np

distance1 = np.array([[0.1], [0.2], [0.3]])
distance2 = np.array([[0.4], [0.5], [0.6]])

print(distance1.shape)
print(distance2.shape)
predictions = (distance1 < distance2).astype(int)
print(predictions.shape)

(3, 1)
(3, 1)
(3, 1)


In [11]:
import numpy as np

# 假设 self.A 是一个 2x2 的数组
A = np.array([[1, 2], [3, 4]])
# 假设 self.beta 是一个长度为 2 的数组
beta = np.array([[0.000], [0.002]])

# 生成布尔数组
mask = beta > 1e-5
mask = mask.flatten()
print(A[mask])


[[3 4]]


In [12]:
import numpy as np

distance1 = np.array([0.1, 0.2, 0.3])
distance2 = np.array([0.4, 0.5, 0.6])

print(distance1.shape)
print(distance2.shape)
predictions = (distance1 < distance2).astype(int)
print(predictions.shape)

(3,)
(3,)
(3,)


In [13]:
A = np.array([[1, 2], [3, 4], [5, 6]])  # 3x2
x = np.array([1,2]) # 3,
print(A.shape)
print(x.shape)
print(np.dot(A, x).shape)

(3, 2)
(2,)
(3,)


In [14]:
import numpy as np

# 创建一个一维 numpy 数组
arr1 = np.array([1, 2, 3])
arr2 = np.array([4,5,6])
# 创建一个空列表
my_list = []

# 将一维 numpy 数组追加到列表中
my_list.append(arr1)
my_list.append(arr2)

print(np.array(my_list).T)

[[1 4]
 [2 5]
 [3 6]]


In [15]:
A = np.array([[1, 2], [3, 4], [5, 6]])  # 3x2
x = np.array([
    [1],
    [2]
]) # 3,
print(A.shape)
print(x.shape)
print(np.dot(A, x).shape)

(3, 2)
(2, 1)
(3, 1)


In [16]:
import numpy as np
A = np.array([[1, 2], [3, 4], [5, 6]])  # 3x2
B = np.array([[1, 2], [3, 4], [5, 6]])  # 3x2
print(np.vstack((A, B)))

[[1 2]
 [3 4]
 [5 6]
 [1 2]
 [3 4]
 [5 6]]


In [17]:
import numpy as np
A = np.array([[1, 2], [3, 4], [5, 6]])  # 3x2
B = np.array([[1, 2], [3, 4], [5, 6]])  # 3x2
print(np.vstack((A, B)))


[[1 2]
 [3 4]
 [5 6]
 [1 2]
 [3 4]
 [5 6]]


In [18]:
import numpy as np
A = np.array([[1, 2,3], [3, 4,5] ])  
B = np.array([[1,2],[3,4]])
print(np.vstack((A, B)))

# 报错，说明符合机器学习的堆叠方式


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [ ]:
a = 'zhong'
b = 'qian'+a+'hao'
print(b)

qianzhonghao


In [ ]:
import numpy as np

# 使用 np.linspace 在0到10之间生成5个等间隔的数字
linspace_result = np.linspace(0, 10, num=5)
print("使用 np.linspace 生成的结果：", linspace_result)

# 使用 np.arange 从0开始，以2为步长，生成小于10的数字
arange_result = np.arange(0, 10, 2)
print("使用 np.arange 生成的结果：", arange_result)
    

使用 np.linspace 生成的结果： [ 0.   2.5  5.   7.5 10. ]
使用 np.arange 生成的结果： [0 2 4 6 8]


In [ ]:
label_cols = {
    'birds': slice(-19, None),  # 假设 birds 数据集最后 19 列是标签列
    'emotions': slice(-6, None),  # 假设 emotions 数据集最后 6 列是标签列
    'flags': slice(-7, None),  # 假设 flags 数据集最后 7 列是标签列
    'yeast': slice(-14, None)  # 假设 yeast 数据集最后 14 列是标签列   
}



In [7]:
import numpy as np
a = np.array(
[[1, 1, 1],
 [0, 1, 0],
 [0, 0, 1]]
)
b = np.array(
[[1, 0, 1],
 [0, 0, 0],
 [0, 1, 1]]
)
print(a==b)
print(np.mean(a==b,axis=1))

[[ True False  True]
 [ True False  True]
 [ True False  True]]
[0.66666667 0.66666667 0.66666667]


In [8]:
import time
import numpy as np

# 生成一个 1000x1000 的随机矩阵
A = np.random.rand(1000, 1000)
B = np.random.rand(1000, 1000)

# 计算矩阵乘法的时间
start_time = time.time()
C = np.dot(A, B)
end_time = time.time()
print("矩阵乘法的时间：", end_time - start_time)

矩阵乘法的时间： 0.03298306465148926


In [25]:
import numpy as np
from sklearn.neighbors import NearestNeighbors
import time
# 示例数据
m, n = 1500,100
C = np.random.rand(m, n)  # 原矩阵C
x = np.random.rand(n)     # 查询向量x


t1 = time.time()
# 创建KNN模型并拟合原矩阵C
k = 5
knn = NearestNeighbors(n_neighbors=k)
knn.fit(C)  

# 查询x的最近邻索引
_, indices = knn.kneighbors(x.reshape(1, -1))  # 返回的indices直接对应C的行号

t2 = time.time()
print("查询时间：", t2 - t1)

# 提取结果（注意indices是二维数组，取第一个元素）
neighbor_row_indices = indices[0]

print("最近邻在C中的行号:", neighbor_row_indices)


查询时间： 0.005548954010009766
最近邻在C中的行号: [106 992 734 343 217]


In [28]:
import numpy as np
a = np.array([
   [1,2,3,4],
   [3,3,3,3],
   [5,5,6,7]
])
for row in a:
    print(row)
    print(row.shape)

[1 2 3 4]
(4,)
[3 3 3 3]
(4,)
[5 5 6 7]
(4,)


In [36]:
import numpy as np
a = np.array([
   [1,1,0,1],
   [0,1,0,0],
   [0,1,1,0]
])
b = np.array([
   [3,2,1,1],
   [1,1,3,0],
   [4,1,1,0]
])
y = a[:,0]
print(y)
# 提取y中为1的索引
idx = (y==1)
print(b[y==1])


[1 0 0]
[[3 2 1 1]]


In [45]:
import numpy as np
from sklearn.neighbors import NearestNeighbors





def get_V(X,Y,k):
    m = Y.shape[1]
    knn = NearestNeighbors(n_neighbors=k)
    knn.fit(X)
    V = []
    for i in range(m):
        y = Y[:,i]
        B = X[(y==0)]
        v = []
        for x in B:
            _, indices = knn.kneighbors(x.reshape(1, -1)) 
            neighbor_idx = indices[0]
            yy = y[neighbor_idx]
            v.append(np.mean(yy))
    V.append(v)
    return V



print(get_V(a,b,2))

[[np.float64(0.0), np.float64(0.0)]]


In [59]:
import numpy as np

a = [[1,2,3],
     [2,2,2,2,2],
     [1,2,2,2],
     [1]
     ]
print(a[3])

[1]


In [60]:
import numpy as np
a = np.ones(3)
b = np.ones(4)
c = np.ones(5)
d = np.ones(6)
ee = []
ee.append(a)
ee.append(b)
ee.append(c)
ee.append(d)
print(ee[1])

[1. 1. 1. 1.]
