In [3]:
import numpy as np

distance1 = np.array([[0.1], [0.2], [0.3]])
distance2 = np.array([[0.4], [0.5], [0.6]])

print(distance1.shape)
print(distance2.shape)
predictions = (distance1 < distance2).astype(int)
print(predictions.shape)

(3, 1)
(3, 1)
(3, 1)


In [10]:
import numpy as np

# 假设 self.A 是一个 2x2 的数组
A = np.array([[1, 2], [3, 4]])
# 假设 self.beta 是一个长度为 2 的数组
beta = np.array([[0.000], [0.002]])

# 生成布尔数组
mask = beta > 1e-5
mask = mask.flatten()
print(A[mask])


[[3 4]]


In [4]:
import numpy as np

distance1 = np.array([0.1, 0.2, 0.3])
distance2 = np.array([0.4, 0.5, 0.6])

print(distance1.shape)
print(distance2.shape)
predictions = (distance1 < distance2).astype(int)
print(predictions.shape)

(3,)
(3,)
(3,)


In [5]:
A = np.array([[1, 2], [3, 4], [5, 6]])  # 3x2
x = np.array([1,2]) # 3,
print(A.shape)
print(x.shape)
print(np.dot(A, x).shape)

(3, 2)
(2,)
(3,)


In [3]:
import numpy as np

# 创建一个一维 numpy 数组
arr1 = np.array([1, 2, 3])
arr2 = np.array([4,5,6])
# 创建一个空列表
my_list = []

# 将一维 numpy 数组追加到列表中
my_list.append(arr1)
my_list.append(arr2)

print(np.array(my_list).T)

[[1 4]
 [2 5]
 [3 6]]


In [6]:
A = np.array([[1, 2], [3, 4], [5, 6]])  # 3x2
x = np.array([
    [1],
    [2]
]) # 3,
print(A.shape)
print(x.shape)
print(np.dot(A, x).shape)

(3, 2)
(2, 1)
(3, 1)


In [ ]:
import numpy as np
A = np.array([[1, 2], [3, 4], [5, 6]])  # 3x2
B = np.array([[1, 2], [3, 4], [5, 6]])  # 3x2
print(np.vstack((A, B)))

[[1 2]
 [3 4]
 [5 6]
 [1 2]
 [3 4]
 [5 6]]


In [1]:
import numpy as np
A = np.array([[1, 2], [3, 4], [5, 6]])  # 3x2
B = np.array([[1, 2], [3, 4], [5, 6]])  # 3x2
print(np.vstack((A, B)))


[[1 2]
 [3 4]
 [5 6]
 [1 2]
 [3 4]
 [5 6]]


In [2]:
import numpy as np
A = np.array([[1, 2,3], [3, 4,5] ])  
B = np.array([[1,2],[3,4]])
print(np.vstack((A, B)))

# 报错，说明符合机器学习的堆叠方式


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 2

In [1]:
a = 'zhong'
b = 'qian'+a+'hao'
print(b)

qianzhonghao


In [1]:
import numpy as np

# 使用 np.linspace 在0到10之间生成5个等间隔的数字
linspace_result = np.linspace(0, 10, num=5)
print("使用 np.linspace 生成的结果：", linspace_result)

# 使用 np.arange 从0开始，以2为步长，生成小于10的数字
arange_result = np.arange(0, 10, 2)
print("使用 np.arange 生成的结果：", arange_result)
    

使用 np.linspace 生成的结果： [ 0.   2.5  5.   7.5 10. ]
使用 np.arange 生成的结果： [0 2 4 6 8]
